### ISSUE TITLE
ping

### ISSUE THREAD

**Issue by yulus420** [amprocode/Bloxflip-rain-notifier#1]
i changed the numbers with everyone and it shows this when i open application:
Traceback (most recent call last):
  File "main.py", line 12, in <module>
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 7 column 19 (char 154)
[8504] Failed to execute script 'main' due to unhandled exception!

**Comment by amprocode** [comment]
As a temporary fix you can put quotes around it so it will look like this:
```
"webhook_ping": "everyone",
```

I plan to update this and fix this issue at a later date

**Comment by amprocode** [comment]
This issue should now be fixed in v1.3.2
I have also added some more documentation on this setting so it should be easier to setup
